#!/usr/bin/env python
# encoding: utf-8

from __future__ import absolute_import, division, print_function

import sys
import pandas as pd


GROUPS = {
    "Gruppe 1": "Do 8:00, Neubau THP Konferenzraum 1 TP",
    "Gruppe 2": "Do 14:00, Altbau Hörsaal II",
    "Gruppe 3": "Do 10:00, Neubau THP Konferenzraum 2 TP",
    "Gruppe 4": "Do 14:00, Altbau Seminarraum 1 Physik",
    "Gruppe 5": "Do 14:00, Altbau Konferenzraum Theorie",
    "Gruppe 6": "Do 14:00, Neubau Konferenzraum 2 TP",
    "Gruppe 7": "Do 17:45, Altbau Hörsaal III",
    "Gruppe 8": "Do 17:45, Altbau Seminarraum 1 Physik",
    "Gruppe 9": "Do 17:45, Altbau Seminarraum 2 Physik",
    "Gruppe 10": "Do 17:45, Altbau Seminarraum Kernphysik"
}

HEADER = """
<html>
  <head>
    <title>Mathematische Methoden WS 15/16</title>
    <link rel="stylesheet" href="style.css" type="text/css">
    <meta charset="utf-8">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>Vorname</th>
        <th>Gruppe</th>
        <th>Zeit/Ort</th>
      </tr>
 """

FOOTER = """
    </table>
  </body>
</html>
"""

assert len(sys.argv) > 1, str(sys.argv)
FNAME = sys.argv[1]

df = pd.read_csv(FNAME)[['\xef\xbb\xbf"Gruppe"', 'Familien- oder Nachname', 'Vorname']]
df.columns = ['group', 'name', 'firstname']
df.replace(to_replace="Gruppe 2 (neuer Termin, siehe Website)", value="Gruppe 2",
           inplace=True)
df.sort("name", inplace=True)

with open('students.html', 'wa') as of:
    of.write(HEADER)

    for _, entry in df.iterrows():
        of.write("<tr>")
        of.write("<td>{name!s}</td><td>{firstname!s}</td><td>{group!s}</td>".format(**entry))
        of.write("<td>{}</td>".format(GROUPS[entry['group']]))
        of.write("</tr>")

    of.write(FOOTER)
